# Выполнено студентом группы УБСТ2202 Трошиным В.А.

name: Trivy Scan Docker Image

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy via Docker
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --exit-code 1 --severity HIGH,CRITICAL alpine/openssl:latest
